-- Floor 1 barrier IDs: OffOutQuestBarrierIDs union from all QST manifests + regional Barrier_/BS_ IDs
-- observed in the save state (ServerDecideQuest). Used to grow OffOutQuestBarrierIDs.
return {
  "BS_Forest2_1_03_3",
  "BS_Plains3_1_01_1",
  "Barrier_0032_3",
  "Barrier_Forest2_1_01",
  "Barrier_Hills2_1_02",
  "Barrier_Plains1_1_04",
  "Barrier_Plains2_1_03",
  "Barrier_Plains2_1_05",
  "Barrier_Plains3_1_01",
  "Barrier_Plains3_1_02",
  "Barrier_Plains3_1_04",
  "OutQuestBarrier_Boss_QST_Main_0012_1",
  "WayEntBarrier_ERU_Dep",
  "WayEntBarrier_ERU_Kati",
  "WayEntBarrier_ERU_Nebeka",
  "WayEntBarrier_ERU_Qiyu",
  "WayEntBarrier_HFO_Def",
  "WayEntBarrier_HFO_Ruin",
  "WayEntBarrier_HTE_Ruin",
  "WayEntBarrier_HTE_Und",
  "WayEntBarrier_MGK_CHM_02",
  "WayEntBarrier_MGK_LA01",
  "WayEntBarrier_MGK_Test",
  "WayEntBarrier_NTR_Blue",
  "WayEntBarrier_NTR_Demi",
  "WayEntBarrier_NTR_Twilight",
  "WayEntBarrier_NTR_Und",
}
