-- ModMenu registry — compatibility contracts for supported mods.
--
-- Auto-discovery is performed by registry.lua. This file remains the explicit
-- allow-list and defines the exact settings that ModMenu may expose.
--
-- entry fields
--   mod       folder name under Mods/. Must match exactly.
--   label     row label in the menu.
--   summary   one line shown under the label.
--   apply     when a change takes effect:
--               "live"    immediately
--               "menu"    next time the start menu is opened
--               "restart" next time the game is launched
--   settings  list of tunables, in display order.
--
-- setting fields
--   key       the name written to runtime.lua, exactly as the mod reads it.
--   label     row label.
--   type      "bool" | "number" | "choice"
--   default   documented config.lua value, used only as registry documentation.
--   min/max   inclusive bounds for "number". Must match the target validator.
--   step      increment per left/right press for "number".
--   format    string.format pattern for displaying a "number".
--   options   list of { value, label } for "choice".
--   apply     optional per-setting override of the mod-level apply.

return {
    {
        mod = "SpeedMod",
        label = "Speed",
        summary = "Sprint acceleration on open terrain",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "START_SPEED", label = "Starting speed", type = "number",
              default = 1.40, min = 1.00, max = 2.50, step = 0.05,
              format = "%.2fx", ceilingKey = "MAX_SPEED" },
            { key = "MAX_SPEED", label = "Top speed", type = "number",
              default = 3.20, min = 1.00, max = 20.00, step = 0.10,
              format = "%.2fx", floorKey = "START_SPEED" },
            { key = "SECONDS_TO_MAX_SPEED", label = "Time to top speed", type = "number",
              default = 1.80, min = 0.25, max = 10.00, step = 0.05, format = "%.2fs" },
            { key = "JUMP_HEIGHT_MULTIPLIER", label = "Jump height", type = "number",
              default = 1.00, min = 0.25, max = 15.00, step = 0.25, format = "%.2fx" },
            { key = "DISABLE_IN_COMBAT", label = "Off during combat", type = "bool",
              default = true },
        },
    },

    {
        mod = "AutoPickupMod",
        label = "Auto Pickup",
        summary = "Collect drops without walking onto them",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "PICKUP_RANGE", label = "Pickup range", type = "number",
              default = 1000, min = 100, max = 5000, step = 100, format = "%.0f cm" },
            { key = "ICON_DISPLAY_RANGE", label = "Icon range", type = "number",
              default = 1500, min = 100, max = 5000, step = 100, format = "%.0f cm" },
            { key = "PICKUP_INTERVAL", label = "Scan interval", type = "number",
              default = 0.30, min = 0.05, max = 2.00, step = 0.05, format = "%.2fs" },
            { key = "SHOW_PICKUP_UI", label = "Pickup notification", type = "bool",
              default = true },
            { key = "EXPAND_OPERATABLE", label = "Widen prompt area", type = "bool",
              default = true },
            { key = "ICON_RANGE_PATCH", label = "Patch icon distance", type = "bool",
              default = true },
            { key = "DEBUG_HOOKS", label = "Debug logging", type = "bool", default = false },
        },
    },

    {
        mod = "norescue",
        label = "No Rescue",
        summary = "Real falls: no edge rescue, no fall-death warp",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "SAFETY_NET_MS", label = "Re-apply interval", type = "number",
              default = 5000, min = 1000, max = 30000, step = 1000, format = "%.0f ms" },
            { key = "DEBUG_LOGS", label = "Debug logging", type = "bool", default = false },
        },
    },

    {
        mod = "FieldEquipPro",
        label = "Field Equip Pro",
        summary = "Equipment entry in this menu",
        apply = "menu",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "SHOW_CHARACTER", label = "Show character",
              type = "bool", default = true },
            { key = "CAMERA_HEIGHT", label = "Camera height", type = "number",
              default = 50, min = -100, max = 200, step = 5, format = "%+.0f cm" },
            { key = "DEBUG_LOGS", label = "Debug logging", type = "bool", default = true },
        },
    },

    {
        mod = "FastTravelMod",
        label = "Fast Travel",
        summary = "Teleport to selected checkpoints and map pins",
        apply = "menu",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "DEBUG_LOGS", label = "Debug logging",
              type = "bool", default = false },
        },
    },

    {
        mod = "ExperienceNotifications",
        label = "XP Notifications",
        summary = "Show EXP earned from each enemy",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "DEBUG_LOGS", label = "Debug logging",
              type = "bool", default = false },
        },
    },

    {
        mod = "GaugeNumbers",
        label = "Gauge Numbers",
        summary = "Live HP, Stamina and SP values plus an EXP bar on the HUD",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "SHOW_HP", label = "HP readout", type = "bool", default = true },
            { key = "SHOW_STAMINA", label = "Stamina readout",
              type = "bool", default = true },
            { key = "SHOW_SP", label = "SP readout", type = "bool", default = true },
            { key = "READOUT_LAYER", label = "Draw layer",
              type = "choice", default = "front", options = {
                  { value = "front", label = "In front of the bars" },
                  { value = "inside", label = "Inside the bar" },
                  { value = "gauge", label = "Gauge assembly" },
              } },
            { key = "HP_X", label = "HP readout X", type = "number",
              default = 198.0, min = 0.0, max = 1920.0, step = 2.0,
              format = "%.0f px" },
            { key = "HP_Y", label = "HP readout Y", type = "number",
              default = 92.0, min = 0.0, max = 1080.0, step = 2.0,
              format = "%.0f px" },
            { key = "STAMINA_X", label = "Stamina readout X", type = "number",
              default = 189.0, min = 0.0, max = 1920.0, step = 2.0,
              format = "%.0f px" },
            { key = "STAMINA_Y", label = "Stamina readout Y", type = "number",
              default = 126.0, min = 0.0, max = 1080.0, step = 2.0,
              format = "%.0f px" },
            { key = "SP_X", label = "SP readout X", type = "number",
              default = 161.0, min = 0.0, max = 1920.0, step = 2.0,
              format = "%.0f px" },
            { key = "SP_Y", label = "SP readout Y", type = "number",
              default = 155.0, min = 0.0, max = 1080.0, step = 2.0,
              format = "%.0f px" },
            { key = "READOUT_PLACEMENT", label = "Readout position",
              type = "choice", default = "center", options = {
                  { value = "center", label = "Centred on the bar" },
                  { value = "right", label = "Off the end" },
              } },
            { key = "ALIGN_READOUTS", label = "Align readouts",
              type = "bool", default = true },
            { key = "VALUE_FORMAT", label = "Readout format", type = "choice",
              default = "current_max", options = {
                  { value = "current_max", label = "280 / 280" },
                  { value = "current", label = "280" },
                  { value = "percent", label = "100%" },
              } },
            { key = "TEXT_OFFSET_X", label = "Readout offset X", type = "number",
              default = -8.0, min = -400.0, max = 400.0, step = 2.0,
              format = "%+.0f px" },
            { key = "TEXT_OFFSET_Y", label = "Readout offset Y", type = "number",
              default = -18.0, min = -400.0, max = 400.0, step = 2.0,
              format = "%+.0f px" },
            { key = "FONT_SIZE", label = "Font size", type = "number",
              default = 11.0, min = 6.0, max = 48.0, step = 1.0, format = "%.0f" },
            { key = "SHOW_EXP", label = "Experience block",
              type = "bool", default = true },
            { key = "SHOW_EXP_BAR", label = "Experience bar",
              type = "bool", default = true },
            { key = "SHOW_EXP_TEXT", label = "Experience numbers",
              type = "bool", default = true },
            { key = "SHOW_EXP_LEVEL", label = "Level prefix",
              type = "bool", default = true },
            { key = "EXP_STYLE", label = "Experience bar style", type = "choice",
              default = "native", options = {
                  { value = "native", label = "Game's own gauge" },
                  { value = "flat", label = "Flat bar" },
              } },
            { key = "EXP_ANCHOR", label = "Experience anchor", type = "choice",
              default = "hp", options = {
                  { value = "hp", label = "HP bar" },
                  { value = "stamina", label = "Stamina bar" },
                  { value = "sp", label = "SP bar" },
              } },
            { key = "EXP_PLACEMENT", label = "Experience side", type = "choice",
              default = "above", options = {
                  { value = "above", label = "Above the gauge" },
                  { value = "below", label = "Below the gauge" },
              } },
            { key = "EXP_OFFSET_X", label = "Experience offset X", type = "number",
              default = 0.0, min = -400.0, max = 400.0, step = 2.0,
              format = "%+.0f px" },
            { key = "EXP_OFFSET_Y", label = "Experience offset Y", type = "number",
              default = -4.0, min = -400.0, max = 400.0, step = 2.0,
              format = "%+.0f px" },
            { key = "EXP_BAR_WIDTH", label = "Experience bar width", type = "number",
              default = 0.0, min = 0.0, max = 1200.0, step = 10.0,
              format = "%.0f px" },
            { key = "EXP_BAR_HEIGHT", label = "Experience bar height", type = "number",
              default = 0.0, min = 0.0, max = 40.0, step = 1.0, format = "%.0f px" },
            { key = "REFRESH_MS", label = "Reconcile interval", type = "number",
              default = 500, min = 100, max = 5000, step = 50, format = "%.0f ms" },
            { key = "DEBUG_LOGS", label = "Debug logging",
              type = "bool", default = false },
        },
    },

    {
        mod = "WorldEnemyDirector",
        label = "Enemy Director",
        summary = "Multiply and mutate world enemies",
        apply = "live",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "SPAWN_MULTIPLIER", label = "Spawn multiplier", type = "number",
              default = 1, min = 1, max = 8, step = 1, format = "%.0fx" },
            { key = "MAX_ACTIVE_EXTRAS", label = "Maximum extras", type = "number",
              default = 48, min = 0, max = 200, step = 4, format = "%.0f" },
            { key = "SPAWN_RADIUS", label = "Spawn radius", type = "number",
              default = 300, min = 100, max = 1500, step = 50, format = "%.0f cm" },
            { key = "DESPAWN_RADIUS", label = "Despawn distance", type = "number",
              default = 6000, min = 1500, max = 30000, step = 500,
              format = "%.0f cm" },
            { key = "SPAWN_IN_EMPTY_AREAS", label = "Spawn in empty areas",
              type = "bool", default = true },
            { key = "RANDOMIZE_EXTRA_SPECIES", label = "Random extra species",
              type = "bool", default = false },
            { key = "INCLUDE_BOSSES", label = "Mutate bosses",
              type = "bool", default = false },
            { key = "SCALE_MIN", label = "Minimum scale", type = "number",
              default = 1.0, min = 0.25, max = 4.0, step = 0.25,
              format = "%.2fx", ceilingKey = "SCALE_MAX" },
            { key = "SCALE_MAX", label = "Maximum scale", type = "number",
              default = 1.0, min = 0.25, max = 4.0, step = 0.25,
              format = "%.2fx", floorKey = "SCALE_MIN" },
            { key = "COLOR_MODE", label = "Colour mode", type = "choice",
              default = "off", options = {
                  { value = "off", label = "Off" },
                  { value = "fixed", label = "Fixed" },
                  { value = "random", label = "Random" },
              } },
            { key = "COLOR_PRESET", label = "Colour preset", type = "choice",
              default = "crimson", options = {
                  { value = "crimson", label = "Crimson" },
                  { value = "emerald", label = "Emerald" },
                  { value = "azure", label = "Azure" },
                  { value = "gold", label = "Gold" },
                  { value = "violet", label = "Violet" },
                  { value = "cyan", label = "Cyan" },
                  { value = "white", label = "White" },
              } },
            { key = "COMMON_HEALTH_MULTIPLIER", label = "Common | Health",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "COMMON_ATTACK_MULTIPLIER", label = "Common | Attack",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "COMMON_DEFENCE_MULTIPLIER", label = "Common | Defence",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "COMMON_MOVE_SPEED_MULTIPLIER",
              label = "Common | Movement speed", type = "number",
              default = 1.0, min = 0.25, max = 3.0, step = 0.05, format = "%.2fx" },
            { key = "COMMON_XP_MULTIPLIER", label = "Common | Experience",
              type = "number",
              default = 1.0, min = 0.0, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "ELITE_HEALTH_MULTIPLIER", label = "Elite | Health",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "ELITE_ATTACK_MULTIPLIER", label = "Elite | Attack",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "ELITE_DEFENCE_MULTIPLIER", label = "Elite | Defence",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "ELITE_MOVE_SPEED_MULTIPLIER",
              label = "Elite | Movement speed", type = "number",
              default = 1.0, min = 0.25, max = 3.0, step = 0.05, format = "%.2fx" },
            { key = "ELITE_XP_MULTIPLIER", label = "Elite | Experience",
              type = "number",
              default = 1.0, min = 0.0, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "BOSS_HEALTH_MULTIPLIER", label = "Boss | Health",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "BOSS_ATTACK_MULTIPLIER", label = "Boss | Attack",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "BOSS_DEFENCE_MULTIPLIER", label = "Boss | Defence",
              type = "number",
              default = 1.0, min = 0.1, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "BOSS_MOVE_SPEED_MULTIPLIER",
              label = "Boss | Movement speed", type = "number",
              default = 1.0, min = 0.25, max = 3.0, step = 0.05, format = "%.2fx" },
            { key = "BOSS_XP_MULTIPLIER", label = "Boss | Experience",
              type = "number",
              default = 1.0, min = 0.0, max = 10.0, step = 0.1, format = "%.1fx" },
            { key = "DEBUG_LOGS", label = "Debug logging",
              type = "bool", default = false },
        },
    },

    {
        mod = "AincradOpenWorld",
        label = "Open World",
        summary = "Any quest opens the entire floor",
        apply = "restart",
        settings = {
            { key = "ENABLED", label = "Enabled", type = "bool", default = true },
            { key = "DEBUG_LOGS", label = "Debug logging", type = "bool", default = false },
            { key = "PROBE_MODE", label = "Research probe", type = "bool", default = false },
        },
    },
}
